defmodule AshDoubleEntry.Test.Repo.Migrations.AddDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:descriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:description, :text, null: false)

      add(
        :transfer_id,
        references(:transfers, column: :id, name: "descriptions_transfer_id_fkey", type: :binary),
        null: false
      )

      add(
        :account_id,
        references(:accounts, column: :id, name: "descriptions_account_id_fkey", type: :uuid),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:descriptions, "descriptions_account_id_fkey"))

    drop(constraint(:descriptions, "descriptions_transfer_id_fkey"))

    drop(table(:descriptions))
  end
end
