defmodule AshDoubleEntry.Description.Transformers.AddStructure do
  @moduledoc false
  use Spark.Dsl.Transformer
  import Spark.Dsl.Builder
  require Ash.Query

  def before?(Ash.Resource.Transformers.SetRelationshipSource), do: true
  def before?(Ash.Resource.Transformers.BelongsToAttribute), do: true
  def before?(Ash.Resource.Transformers.CachePrimaryKey), do: true
  def before?(_), do: false

  def transform(dsl) do
    transfer_resource = AshDoubleEntry.Description.Info.description_transfer_resource!(dsl)
    account_resource = AshDoubleEntry.Description.Info.description_account_resource!(dsl)

    dsl
    |> add_primary_read_action()
    |> Ash.Resource.Builder.add_new_attribute(:id, AshDoubleEntry.ULID,
      primary_key?: true,
      writable?: false,
      generated?: true,
      allow_nil?: false,
      default: &AshDoubleEntry.ULID.generate/0
    )
    |> Ash.Resource.Builder.add_new_attribute(:description, :string, allow_nil?: false)
    |> Ash.Resource.Builder.add_new_action(:create, :add,
      accept: [:description, :account_id, :transfer_id]
    )
    |> Ash.Resource.Builder.add_new_action(:read, :memo,
      description: "Reads descriptions with the associated record loaded",
      preparations: [
        {Ash.Resource.Preparations.Filter, query: &__MODULE__.load_memo/2}
      ]
    )
    |> Ash.Resource.Builder.add_new_action(:read, :by_transfer,
      description: "Reads descriptions filtered by a specific transfer ID",
      arguments: [
        Ash.Resource.Builder.build_action_argument(:transfer_id, AshDoubleEntry.ULID,
          allow_nil?: false
        )
      ],
      preparations: [
        {Ash.Resource.Preparations.Filter, query: &__MODULE__.filter_by_transfer/2}
      ]
    )
    |> Ash.Resource.Builder.add_new_action(:read, :by_account,
      description: "Reads descriptions filtered by a specific account ID",
      arguments: [
        Ash.Resource.Builder.build_action_argument(:account_id, :uuid, allow_nil?: false)
      ],
      preparations: [
        {Ash.Resource.Preparations.Filter, query: &__MODULE__.filter_by_account/2}
      ]
    )
    |> Ash.Resource.Builder.add_new_attribute(:inserted_at, :utc_datetime_usec,
      allow_nil?: false,
      default: &DateTime.utc_now/0
    )
    |> Ash.Resource.Builder.add_new_attribute(:updated_at, :utc_datetime_usec,
      allow_nil?: false,
      default: &DateTime.utc_now/0
    )
    |> Ash.Resource.Builder.add_new_relationship(
      :belongs_to,
      :transfer,
      transfer_resource,
      attribute_type: AshDoubleEntry.ULID,
      allow_nil?: false,
      attribute_writable?: true
    )
    |> Ash.Resource.Builder.add_new_relationship(
      :belongs_to,
      :account,
      account_resource,
      allow_nil?: false,
      attribute_writable?: true
    )
  end

  def load_memo(query, _opts) do
    Ash.Query.load(query, :description_record)
  end

  def filter_by_transfer(query, _opts) do
    transfer_id = Ash.Query.get_argument(query, :transfer_id)
    Ash.Query.filter(query, transfer_id == ^transfer_id)
  end

  def filter_by_account(query, _opts) do
    account_id = Ash.Query.get_argument(query, :account_id)
    Ash.Query.filter(query, account_id == ^account_id)
  end

  defbuilder add_primary_read_action(dsl) do
    if Ash.Resource.Info.primary_action(dsl, :read) do
      {:ok, dsl}
    else
      Ash.Resource.Builder.add_action(dsl, :read, :_autogenerated_primary_read,
        primary?: true,
        pagination: Ash.Resource.Builder.build_pagination(keyset?: true, required?: false)
      )
    end
  end
end
